<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DungeonGame</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Angel player.png" />
    <None Remove="Assets\Choose character.png" />
    <None Remove="Assets\Stitch Player.png" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
    <Import Include="System.Windows.Shapes" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Angel player.png" />
    <Resource Include="Assets\Choose character.png" />
    <Resource Include="Assets\Stitch Player.png" />
  </ItemGroup>

</Project>
